### ISSUE TITLE
Contour density with weights

### ISSUE THREAD

**Issue by JNDanielson** [joferkington/mplstereonet#19]
I tried using the 'weights = ' option in the density_contourf function to apply Terzaghi Weighting

`cax = ax0.density_contourf(strikes, dips, measurement='poles',cmap='inferno',weights = Weights)`

And got the following error:
> Truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()

The code works fine when weights is omitted or =None.

Looks like the following line in def_count_point was the problem, and it fails because weights is an arraylike: 
```
   if weights in (None, False):
        weights = 1
```

I kludged together the following fix to get the code to work
```
    try:
        if weights in (None, False):
            weights = 1
    # Normalize the weights
    except:
        weights = np.asarray(weights, dtype=np.float)
        weights /= weights.mean()
```
But I can't code at all - I'm sure you can find a much better solution.

Thank you so much for this fantastic library.

**Comment by joferkington** [comment]
Hi @JNDanielson,

My sincere apologies for your issue getting ignored for so long! I've been distracted by other work for the past year or two.  

At any rate, the issue should be fixed in https://github.com/joferkington/mplstereonet/commit/0b95e9bf4aa0654ebc955780dc58b0c15063a83d

Thanks for finding it and filing a report!
